### ISSUE TITLE
After upgrade to 2.* bigint array generates incorrect type

### ISSUE THREAD

**Issue by pnispel** [adelsz/pgtyped#506]
**Describe the bug**
Environment:
typescript@5.0.2
pgtyped*@2.1.0

```
\df graphile_worker.complete_jobs
                                     List of functions
     Schema      |     Name      |      Result data type      | Argument data types | Type
-----------------+---------------+----------------------------+---------------------+------
 graphile_worker | complete_jobs | SETOF graphile_worker.jobs | job_ids bigint[]    | func
(1 row)
```

```
sql`
  select * from graphile_worker.complete_jobs($$jobIds);
`
```

results in

```
export type number | stringArray = (number | string)[];
```

```
Type alias name cannot be 'number'.
'=' expected.ts(1005)
Cannot find name 'stringArray'.ts(2304)
Exported type alias 'number' has or is using private name 'stringArray'.ts(4081)
```

**Expected behavior**
Builds proper types

**Comment by JarSeal** [comment]
Just to confirm we have this issue as well.

**Comment by moroumo** [comment]
Replacing the line to `export type stringArray = (string)[];` in the generated file may work. but it's just a workaround, it may be overridden by next generating (not tested this), still need a fix.

thanks

**Comment by leifniem** [comment]
Ran into it as well with a dynamic query parameter that handles ids. I'll see if i can find anything in the code.

**Comment by leifniem** [comment]
FTR: #521 
It's a very simple fix as it seems.

**Comment by KhaledElmorsy** [comment]
Just ran into this issue too.

**Comment by adelsz** [comment]
Fixed in #521
